server.port=8081
spring.application.name=sgbp-biblioteca

# Tentando as duas chaves para não ter erro na v4.0.5
spring.data.mongodb.uri=mongodb+srv://lucas_db_admin:be4cK7cwBgdw8PaP@sgbp-library.szmclca.mongodb.net/SGBP_Database?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://lucas_db_admin:be4cK7cwBgdw8PaP@sgbp-library.szmclca.mongodb.net/SGBP_Database?retryWrites=true&w=majority

# Isso aqui vai mostrar no console se ele está tentando conectar mesmo
logging.level.org.mongodb.driver=DEBUG